export const DESPIECE_COLUMNS = [
  {
    key: 'cantidad',
    label: 'CANT',
    className: 'col-cantidad',
    inputType: 'number',
    align: 'center',
    placeholder: '0',
    step: '1',
    min: '1',
    width: '5%',
    minWidth: '32px',
  },
  {
    key: 'largo',
    label: 'LARGO',
    className: 'col-largo',
    inputType: 'number',
    align: 'right',
    step: 'any',
    width: '5%',
    minWidth: '32px',
  },
  {
    key: 'ancho',
    label: 'ANCHO',
    className: 'col-ancho',
    inputType: 'number',
    align: 'right',
    step: 'any',
    width: '5%',
    minWidth: '32px',
  },
  {
    key: 'detalle',
    label: 'DETALLE MATERIAL',
    className: 'col-detalle',
    inputType: 'text',
    align: 'left',
    placeholder: 'Detalle',
    width: '48%',
    minWidth: '260px',
  },
  {
    key: 'rotar',
    label: 'ROTAR',
    className: 'col-rotar',
    inputType: 'text',
    inputMode: 'numeric',
    align: 'center',
    maxLength: 1,
    placeholder: '1',
    width: '5%',
    minWidth: '32px',
  },
  {
    key: 'l1',
    label: 'L1',
    className: 'col-l1',
    inputType: 'text',
    inputMode: 'numeric',
    align: 'center',
    maxLength: 1,
    placeholder: 'Ref',
    width: '5%',
    minWidth: '32px',
  },
  {
    key: 'l2',
    label: 'L2',
    className: 'col-l2',
    inputType: 'text',
    inputMode: 'numeric',
    align: 'center',
    maxLength: 1,
    placeholder: 'Ref',
    width: '5%',
    minWidth: '32px',
  },
  {
    key: 'a1',
    label: 'A1',
    className: 'col-a1',
    inputType: 'text',
    inputMode: 'numeric',
    align: 'center',
    maxLength: 1,
    placeholder: 'Ref',
    width: '5%',
    minWidth: '32px',
  },
  {
    key: 'a2',
    label: 'A2',
    className: 'col-a2',
    inputType: 'text',
    inputMode: 'numeric',
    align: 'center',
    maxLength: 1,
    placeholder: 'Ref',
    width: '5%',
    minWidth: '32px',
  },
];

export const DESPIECE_ACTIONS_COLUMN = {
  width: '12%',
  minWidth: '80px',
};

export const DESPIECE_HEADER_GROUPS = [
  { label: 'MEDIDAS', colSpan: 3 },
  { label: '', colSpan: 2 },
  { label: 'CANTO', colSpan: 4 },
];
